--- 
listen_port: ":50051"
redis_key: "gResponseList"
redis_addr: "localhost:6379"
redis_pass: ""
redis_db: 0
req_url: "https://www.googleapis.com/customsearch/v1"
req_cx: ""
req_key: ""
req_num: "10"
